export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED_PENDING_HCM = 'APPROVED_PENDING_HCM',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
